### ISSUE TITLE
TypeError: Cannot read property 'startWithAppkey' of undefined

### ISSUE THREAD

**Issue by beysong** [yyyyu/react-native-mta#1]
mta.startWithAppkey({ appKey: 'appKey' })
  .then(res => { console.log(res) })
  .catch(err => { console.error(err) })
这里会报错
TypeError: Cannot read property 'startWithAppkey' of undefined

**Comment by yvvw** [comment]
确定有正确添加依赖吗，log一下mta对象，看看结构里面是否包含startWithAppkey方法，我有测试依赖的repository，https://github.com/yyyyu/RNModuleTest/tree/react-native-mta 可以参考一下

**Comment by beysong** [comment]
@yyyyu 打印出来是包含startWithAppkey方法的，项目是原生项目里面有部分模块是react native，猜测是原来的项目已经引入mta sdk了，可能是sdk冲突了
后来想想,应该把埋点方法从原生 传到rn，实践下来是可以的
